name: CKD Bot Actions

on:
  schedule:
    # 한국 시간(KST) 기준: 09:47, 11:47, 13:47, 15:47
    # UTC 시간 기준 (KST - 9시간): 00:47, 02:47, 04:47, 06:47
    - cron: '47 0 * * *'  # 09:47 KST
    - cron: '47 2 * * *'  # 11:47 KST
    - cron: '47 4 * * *'  # 13:47 KST
    - cron: '47 6 * * *'  # 15:47 KST
  workflow_dispatch: # 수동 실행 버튼

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      # v3 -> v4로 업데이트
      - uses: actions/checkout@v4
      
      # v4 -> v5로 업데이트
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install Lib
        run: pip install requests
        
      - name: Run Script
        env:
          DATA_GO_KR_API_KEY: ${{ secrets.DATA_GO_KR_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
